# Generated by Django 3.1.7 on 2021-03-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegBodies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('short_state', models.CharField(max_length=2)),
                ('body', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('sponsor', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=64)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.legbodies')),
                ('short_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bills', to='tracker.legbodies')),
            ],
        ),
    ]
