# Generated by Django 3.1.7 on 2021-03-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210329_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=64),
        ),
    ]
