# Generated by Django 3.1.7 on 2021-03-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210329_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='date',
            field=models.CharField(default='00/00/0000', max_length=10),
        ),
    ]
