# Generated by Django 3.1.7 on 2021-04-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210329_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='legBody',
            new_name='legislature',
        ),
    ]
